#!/usr/bin/python
import csv
import time
import datetime
import os
from naLibSorting import  sortTasksCSV 

def getTaskAges():
	tasklist=sortTasksCSV()
	now=0
	dayold=0
	threedayold=0
	weekold=0
	for row in tasklist:
		try:
			datestring=row[3]
			dateOfTask=time.strptime(datestring.strip(),'%Y-%m-%d (%a) -  %H:%M:%S')
			age=time.time()- time.mktime(dateOfTask)
			now=now+1
			if age>60*60*24:
				dayold=dayold+1
			if age>60*60*24*3:
				threedayold=threedayold+1
			if age>60*60*24*7:
				weekold=weekold+1
		except : 
			print row

			pass
	print str(now)+" "+ str(datetime.date.today()) +" "+str(int(time.time()))+" "+ str(weekold)+" "+str(dayold)+" "+str(threedayold)
	return (now,dayold,threedayold,weekold)

if __name__ == '__main__': getTaskAges()
