#!/usr/bin/python
import csv
import time
import datetime
import operator
import io
import os
from na_lib_sorting import get_sorted_actions
from na_lib_sorting import TIMESTAMP_FORMAT


def print_sorted_tasks():
        tasklist = get_sorted_actions()
        for row in tasklist:
                date = row[4]
                timestamp_on_action = datetime.datetime.strptime(date.strip(), TIMESTAMP_FORMAT)
		date=timestamp_on_action+ datetime.timedelta(days=1)
		date=date.strftime(TIMESTAMP_FORMAT)
                toprint = "%s, %s, %2s, \"%s\", %s" % (
                        row[0].strip(),  row[1].strip(), row[2], row[3], date)
                if len(row) == 6:
                        toprint = toprint+", "+row[5]
                print toprint

if __name__ == '__main__':
        print_sorted_tasks()
